=== liornaar/Chinese-Checkers-JavaFX-App/src/resources/chinese_checkers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="chinese_checkers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="players" type="players">
                    <xs:unique name="unique-player-name">
                        <xs:selector xpath="player"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                    <xs:unique name="unique-player-colors">
                        <xs:selector xpath="player/color"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                    <xs:unique name="unique-target">
                        <xs:selector xpath="player/colorType/target"/>
                        <xs:field xpath="@row"/>
                        <xs:field xpath="@col"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="board" type="board">
                    <xs:unique name="unique-cell">
                        <xs:selector xpath="cell"/>
                        <xs:field xpath="@row"/>
                        <xs:field xpath="@col"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="current_player" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="players">
        <xs:sequence minOccurs="2" maxOccurs="6">
            <xs:element name="player">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="3">
                        <xs:element name="colorDef" type="colorType"/>
                    </xs:sequence>
                    <xs:attribute name="type" type="playerType" use="required"/>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="playerType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="HUMAN"/>
            <xs:enumeration value="COMPUTER"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLACK"/>
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="RED"/>
            <xs:enumeration value="GREEN"/>
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="YELLOW"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="colorType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="target">
                <xs:complexType>
                    <xs:attributeGroup ref="position"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="color" use="required" type="color"></xs:attribute>
    </xs:complexType>

    <xs:attributeGroup name="position">
        <xs:attribute name="row" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:nonNegativeInteger">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="17"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="col" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:nonNegativeInteger">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="13"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:complexType name="cell">
        <xs:attributeGroup ref="position"/>
        <xs:attribute name="color" use="required" type="color"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="board">
        <xs:sequence  minOccurs="0" maxOccurs="121">
            <xs:element name="cell" type="cell"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== liornaar/Chinese-Checkers-JavaFX-App/src/resources/chinese_checkers.xml
<?xml version="1.0" encoding="UTF-8"?>
<chinese_checkers xsi:noNamespaceSchemaLocation="chinese_checkers.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    current_player="john">
    <players>
        <player type="HUMAN" name="john">
            <colorDef color="GREEN">
                <target row="17" col="1"/>
            </colorDef>
        </player>
        <player type="COMPUTER" name="paul">
            <colorDef color="RED">
                <target row="1" col="1"/>
            </colorDef>
        </player>
    </players>
    <board>
        <cell row="1" col="1" color="GREEN"></cell>
        <cell row="2" col="2" color="GREEN"></cell>
        <cell row="3" col="1" color="GREEN"></cell>
        <cell row="3" col="2" color="GREEN"></cell>
        <cell row="3" col="3" color="GREEN"></cell>
        <cell row="4" col="1" color="GREEN"></cell>
        <cell row="4" col="2" color="GREEN"></cell>
        <cell row="5" col="6" color="GREEN"></cell>
        <cell row="7" col="6" color="GREEN"></cell>
        <cell row="8" col="6" color="GREEN"></cell>
        <cell row="11" col="7" color="RED"></cell>
        <cell row="13" col="8" color="RED"></cell>
        <cell row="14" col="1" color="RED"></cell>
        <cell row="14" col="2" color="RED"></cell>
        <cell row="15" col="1" color="RED"></cell>
        <cell row="15" col="2" color="RED"></cell>
        <cell row="15" col="3" color="RED"></cell>
        <cell row="16" col="1" color="RED"></cell>
        <cell row="16" col="2" color="RED"></cell>
        <cell row="17" col="1" color="RED"></cell>
    </board>
</chinese_checkers>
